# Generated by Django 5.2.4 on 2025-07-11 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_client_alter_machine_consignee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='service_company',
        ),
        migrations.AddField(
            model_name='machine',
            name='service_organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'service'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviced_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная организация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
